#!/bin/bash
# Make sure this file is executable!

git stash -q --keep-index
echo "Checking code style prior to committing..."
./gradlew ktlintCheck
RESULT=$?
git stash pop -q

[ $RESULT -ne 0 ] && exit 1
exit 0