#!/bin/bash
# Make sure this file is executable!

echo "Hook: verifying/enforcing ktlint code compliancy..."
./gradlew ktlintFormat

STATUS=$?

if [ "$STATUS" = 0 ] ; then
    echo "ktlint found no problems."
    exit 0
else
    echo 1>&2 "ktlint found violations it could not fix."
    exit 1
fi
